server:
  port: 8888

#spring:
  #cloud:
    #config:
      #server:
        #git:
          #uri: https://seu-repositorio-git/config-repo
          #search-paths: '{application}'
          #clone-on-start: true


spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:////home/marcos-pc/Desenvolvimento/java      # Caminho local da pasta de configuração
encrypt:
  key: KT4iQQr8zRCIjzvnU8weIpC8XAUOiCRA6wXs1PlYhTc=